// src/components/Home.tsx
import { useEffect, useState } from "react";

export const Home = () => {
    const s = "Hello There!";
    const [currentText, setCurrentText] = useState("");

    let index = 0;

    useEffect(() => {
        const timer = setInterval(() => {
            setCurrentText((prevText) => {
                if (prevText === s) {
                    clearInterval(timer);
                    return prevText;
                }
                index++;
                return s.slice(0, index);
            });
        }, 200);
        return () => clearInterval(timer);
    }, [s]);

    return (
        <h1 style={{
            marginTop: '30vh'
        }}>{currentText}</h1>
    );
}

// src/lib/Routes/Home.svelte
<script lang="ts">
    import { onMount } from "svelte";

    const text = "Hello There!";
    let index = 0;
    let current: string = "";

    onMount(() => {
        let intervalId = setInterval(() => {
            if (current.length === text.length) clearInterval(intervalId);

            current += text.charAt(index);
            index++;
        }, 250);
    });
</script>

<h1>{current}</h1>
