// src/components/inner/Home.tsx
import { createSignal } from "solid-js";

const Home = () => {
    const [count, setCount] = createSignal("");
    const text = "Hello There!"
    let index = 0;

    const interval = setInterval(() => setCount((c) => {
        if (text.length == 0) clearInterval(interval);

        let current_text = c + text.charAt(index);
        index++;

        return current_text;
    }), 100);

    return (
        <h1 class="nice">{count}</h1>
    )
}

export default Home;

// src/lib/Routes/Home.svelte
<script lang="ts">
    import { onMount } from "svelte";

    const text = "Hello There!";
    let index = 0;
    let current: string = "";

    onMount(() => {
        let intervalId = setInterval(() => {
            if (current.length === text.length) clearInterval(intervalId);

            current += text.charAt(index);
            index++;
        }, 250);
    });
</script>

<h1>{current}</h1>
