// src/lib/Routes/Blog.svelte
<script lang="ts">
    import Card from "../Card.svelte";

    let cards = [
        {
            title: "First title!",
            description: "This is an example description for first title.",
        },
        {
            title: "Second title!",
            description: "This is an example description for second title.",
        },
        {
            title: "Third title!",
            description: "This is an example description for third title.",
        },
        {
            title: "Fourth title!",
            description: "This is an example description for fourth title.",
        },
    ];
</script>

<h1><u>Blog items</u></h1>
{#each cards as card}
    <Card {card} />
{/each}

<style>
    h1 {
        margin-bottom: 20px;
    }
</style>

// src/components/Blog.tsx
import { Card } from "./Card"

export const Blog = () => {
    return (
        <>
            <Card
                tags="27th April, 2023"
                title="First title"
                description="Some descriptive description"
            />
            <Card 
                tags="28th March, 2023"
                title="Second title"
                description="Second description that is a little longer than the title"
            />
        </>
    );
}
