// src/lib/Routes/Home.svelte
<script lang="ts">
    import { onMount } from "svelte";

    const text = "Hello There!";
    let index = 0;
    let current: string = "";

    onMount(() => {
        let intervalId = setInterval(() => {
            if (current.length === text.length) clearInterval(intervalId);

            current += text.charAt(index);
            index++;
        }, 250);
    });
</script>

<h1>{current}</h1>

// src/components/Home.jsx

import React, { useState, useEffect, useRef } from 'react';
import './Home.css'

const Home = () => {
	const [currentText, setCurrentText] = useState("")
	const index = useRef(0)
	const text = "Hello!"

	useEffect(() => {
		setTimeout(() => {
			setCurrentText((v) => v + text.charAt(index.current))
			index.current++
		}, 200)
	}, [currentText, text])

	return (
		<div className="home_container">
			<h1>
				{currentText}
			</h1>
		</div>
	);
}

export default Home
